#!/bin/bash
rm *~
rm *.*~
rm .*~
git status
git add .
git status
echo "########################"
echo ""
echo "enter commit message"
echo ""
message=""
read message
echo "enter some detail about changes(Optional)"
detail=""
read detail
git commit -m "$message" -m "$detail"
echo "#############"
echo "Pushing changes"
echo "#############"
git push origin test
echo "changes are published on github"
